theme: jekyll-theme-minimal
title: Authorship patterns in Africa's groundwater literature
description: This interactive web map interface was created for an interactive visualiation of the maps in the publication [Authorship patterns in Africas groundwater literature: Indications for helicopter research?](https://www.sciencedirect.com/science/article/pii/S0012825224001867)
logo: how to use.jpg

