theme: jekyll-theme-minimal
title: Authorship patterns in Africas groundwater literature
description: This interactive web map interface was created for an interactive visualiation of the maps in the publication Authorship patterns in Africas groundwater literature
